# Generated by Django 3.1.5 on 2021-01-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_id', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('shared_text', models.TextField()),
                ('time', models.DateTimeField()),
                ('image', models.TextField()),
                ('video', models.TextField()),
                ('num_reacts', models.IntegerField()),
                ('like_react', models.IntegerField()),
                ('sorry_react', models.IntegerField()),
                ('anger_react', models.IntegerField()),
                ('love_react', models.IntegerField()),
                ('wow_react', models.IntegerField()),
                ('support_react', models.IntegerField()),
                ('haha_react', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('post_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
